version: '2.4'

services:
   data_prepare:
     image: blender_dataset
     container_name: blender_dataset
     runtime: nvidia
     environment:
        NVIDIA_VISIBLE_DEVICES: all
        DISPLAY: $DISPLAY
        LIBUSB_DEBUG: 0
        LIBFREENECT2_PIPELINE: cuda
        QT_X11_NO_MITSHM: 1
        NVIDIA_DRIVER_CAPABILITIES: graphics,compute,utility
        stdin_open: 1
        restart: 'unless-stopped'
        network_mode: host
     volumes:
          - /dev/bus/usb:/dev/bus/usb
          #- /dev/video0:/dev/video0
          - /tmp/.X11-unix:/tmp/.X11-unix
          - $HOME/.Xauthority:/root/.Xauthority
          - /home/nishanth/kidz/synthetic_dataset/blender_data/src:/root/src
          - /home/nishanth/outputs/blender:/root/src/output
     tty: true
     privileged: true
     command: bash -c "tail -f /dev/null"
     #command: 
