version: '2.4'

services:
   data_prepare:
     image: cyclegan_train
     container_name: cyclegan_test
     runtime: nvidia
     environment:
        NVIDIA_VISIBLE_DEVICES: all
        DISPLAY: $DISPLAY
        LIBUSB_DEBUG: 0
        LIBFREENECT2_PIPELINE: cuda
        QT_X11_NO_MITSHM: 1
        NVIDIA_DRIVER_CAPABILITIES: graphics,compute,utility
        stdin_open: 1
        restart: 'unless-stopped'
        network_mode: host
     volumes:
          - /dev/bus/usb:/dev/bus/usb
          #- /dev/video0:/dev/video0
          - /tmp/.X11-unix:/tmp/.X11-unix:rw
          - $HOME/.Xauthority:/root/.Xauthority
          - /home/nishanth/kidz/synthetic_dataset/niryorobot_pipeline/cgan_train/src:/root/src
          - /home/nishanth/kidz/synthetic_dataset/niryorobot_pipeline/cgan_train/checkpoints:/root/checkpoints/
          - /home/nishanth/kidz/synthetic_dataset/niryorobot_pipeline/cgan_test/results:/root/results/
         
     tty: true
     privileged: true
     #command: bash -c "tail -f /dev/null"
     command: bash -c "python3 /root/src/test.py --dataroot /root/src/datasets/parts --name parts_cyclegan --model cycle_gan"